name: Deploy PHP App

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Récupérer le code
        uses: actions/checkout@v2

      - name: Installer PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'

      - name: Lancer le serveur PHP
        run: |
          php -S 0.0.0.0:8080 -t . &
      
      - name: Afficher l'URL
        run: echo "Votre site tourne sur http://localhost:8080"
